### ISSUE TITLE
[error] maybe OBO related 

### ISSUE THREAD

**Issue by inesboxexa** [AlanRace/SpectralAnalysis#42]
Hi Alan,

While using the most recent versus of SA in git and attempting to generate the total spectrum, Rory is getting the following error:

Mar 19, 2021 11:39:58 AM com.alanmrace.jimzmlparser.obo.HTTPOBOLoader getInputStream
SEVERE: Failed to download OBO for use later
javax.net.ssl.SSLException: Received fatal alert: protocol_version
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at com.alanmrace.jimzmlparser.obo.OBO.downloadOBO(OBO.java:189)
    at com.alanmrace.jimzmlparser.obo.HTTPOBOLoader.getInputStream(HTTPOBOLoader.java:16)
    at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:79)
    at com.alanmrace.jimzmlparser.obo.OBO.loadOntologyFromURL(OBO.java:244)
    at com.alanmrace.jimzmlparser.obo.OBO.getOBO(OBO.java:173)
    at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:178)
    at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:156)
    at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:140)
Undefined variable "com" or class "com.alanmrace.JSpectralAnalysis.RegionOfInterest.createROIList".
Error in PostProcessing/setUpFastMethods (line 130)
                this.javaROIList = com.alanmrace.JSpectralAnalysis.RegionOfInterest.createROIList();
Error in TotalSpectrum/process (line 26)
            [canUseFastMethods, workflow] = this.setUpFastMethods(dataRepresentation);

Error in f_saving_spectra_details (line 77)
        totalSpectrum = spectrumGeneration.process(data); % computing total spectrum

Do you have any idea of what might be wrong?

Thank you
Teresa

**Comment by AlanRace** [comment]
Hi Teresa,
This shouldn't be an issue with the OBO - if it fails to download the latest version (as it seems to do here), then it checks the working directory for a file and if that isn't there either it defaults to using the last version that was included with the parser. 

The problematic error seems to be this one: 

```
Undefined variable "com" or class "com.alanmrace.JSpectralAnalysis.RegionOfInterest.createROIList".
Error in PostProcessing/setUpFastMethods (line 130)
this.javaROIList = com.alanmrace.JSpectralAnalysis.RegionOfInterest.createROIList();
Error in TotalSpectrum/process (line 26)
[canUseFastMethods, workflow] = this.setUpFastMethods(dataRepresentation);
```

So it seems that MATLAB isn't recognising the `com.alanmrace.JSpectralAnalysis.RegionOfInterest` class and/or the `createROIList` function. You might want to check which version of `JSpectralAnalysis.jar` is being loaded and whether any function from that .jar is callable. If it's loaded, but you can't call any function then perhaps it's a version mismatch with MATLAB and Java?

Alan
