### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JeremyLilili** [AlanRace/SpectralAnalysis#48]
**Describe the bug**
Hi Alan:
    I'm a new user in SpectralAnalysis. After I run the code you provide, I found here comes an error.If possible,could you help me to solve this?

Many Thanks
Jeremy

**To Reproduce**
1. Run the code.
2. Press the ImzML button in Open and choose MouseBrainCerebellum.imzML in the example folder.
3. See error that shows "Java exception occurred:".

**Expected behavior**
The data should be showed from the viewer.

**Screenshots**
![123](https://user-images.githubusercontent.com/100220369/155169260-df4e4dfe-fe98-42b9-8758-add518f2d10d.jpg)

Error using ImzMLParser/parse (line 56)
Java exception occurred:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

	at java.lang.String.substring(String.java:1967)

	at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:115)

	at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)

	at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)

	at com.alanmrace.jimzmlparser.obo.OBO.loadOntologyFromFile(OBO.java:252)

	at com.alanmrace.jimzmlparser.obo.OBO.getOBO(OBO.java:169)

	at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:178)

	at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:156)

	at com.alanmrace.jimzmlparser.parser.ImzMLHandler.parseimzML(ImzMLHandler.java:140)

Error in SpectralAnalysisInterface/openFile (line 79)
                        parser.parse();

Error in SpectralAnalysisInterface>@(src,evnt)this.openFile(this.openFileMethods{i}) (line 330)
                    'Callback', @(src, evnt) this.openFile(this.openFileMethods{i}));
 
Error while evaluating Menu Callback.

**Software version**
- Version number 1.4.0-38ce932
- Source code

**If using source code, MATLAB version (please complete the following information):**
 - MATLAB R2021b

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [ Windows 10]

**Additional context**

**Comment by YaqiZhangAngel** [comment]
Hi Jeremy and Alan,

I was using Matlab 2022 and exactly same issue occurred. Just wondering is there any tips or updates on this issue?
Thanks for the help!

best

**Comment by marcogia87** [comment]
Hello, I am encountering the same issue and I am using the most recent version of MatLab R2024a. Could you help us to solve the issue?
